name: release CI

on:
  # Push激活
  # push:

  # 定时激活
  schedule:
    - cron:  '* 2 * * *'
      # 每30分钟：'30 * * * *'
      # 每1小时：'* 1 * * *'
      # ！最少5分钟

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 运行工具
      - name: Run ReleaseDelivr
        run: |
          ls

      - run: |
          echo "tVer=${{ steps.tVer.outputs.content }}" >> $GITHUB_ENV
          echo "cVer=${{ steps.cVer.outputs.content }}" >> $GITHUB_ENV

      # 读取下载地址
      - name: Read DownloadLink
        if: env.cVer != env.tVer
        id: downloadlink
        uses: juliangruber/read-file-action@v1
        with:
          path: ./download_link

      # 运行工具
      - name: Github Release create, update, and upload assets
        if: env.cVer != env.tVer
        uses: meeDamian/github-release@v2.0.3
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tVer.outputs.content }}
          name: ${{ steps.tVer.outputs.content }}
          body: 下载链接：</br>${{ steps.downloadlink.outputs.content }}


- 定时: 每天
  获取当前仓库的release版本号 -> currentVersion    https://api.github.com/repos/Purple-CSGO/CSGO-Config-Presets/releases/latest
  获取最新版本号 -> targetVersion    https://www.gyan.dev/ffmpeg/builds/git-version  https://www.gyan.dev/ffmpeg/builds/release-version
  if 版本号不同 -> 下载
    https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
    https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z
  发布release

targetVersion=`curl https://www.gyan.dev/ffmpeg/builds/git-version`
