name: release CI

on:
  # Push激活
  push:

  # 定时激活
  schedule:
    - cron:  '0 5 * * *'
      # 每30分钟：'30 * * * *'
      # 每1小时：'* 1 * * *'
      # ！最少5分钟

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 获取对比版本，下载文件
      - name: run
        run: |
          currentVersion=`curl $CURRENT_VERSION_API`
          targetVersion=`curl $TARGET_VERSION_API`

          if [ $currentVersion != $targetVersion ]
          then
            mkdir temp
            cd temp
            echo "Downloading File_1..."
            wget $FILE_1 -q
            echo "Downloading File_2..."
            wget $FILE_2 -q
            echo "CURRENT_VERSION=$currentVersion" >> $GITHUB_ENV
            echo "TARGET_VERSION=$targetVersion" >> $GITHUB_ENV
            cd .
          fi
        env:
          CURRENT_VERSION_API: https://api.upup.cool/repos/Purple-CSGO/CSGO-Config-Presets/version
          TARGET_VERSION_API: https://www.gyan.dev/ffmpeg/builds/git-version
          FILE_1: https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
          FILE_2: https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z

      # 发布release和上传文件
#       - name: release
#         if: env.CURRENT_VERSION != env.TARGET_VERSION
#         uses: meeDamian/github-release@v2.0.3
#         with:
#           token:  ${{ secrets.GITHUB_TOKEN }}
#           tag: ${{ env.TARGET_VERSION }}
#           name: FFMPEG Builds ${{ env.TARGET_VERSION }}
#           body: All files are from https://www.gyan.dev/ffmpeg/
#           files: temp/
#           gzip: false
      
      - name: Create Release With Asset
        id: Release-AIO
        uses: Hs1r1us/Release-AIO@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TARGET_VERSION }}
          asset_files: './temp/'
          release_name: FFMPEG Builds ${{ env.TARGET_VERSION }}
          body: All files are from https://www.gyan.dev/ffmpeg/

